export enum ValidationMessages {
  EMAIL_INVALID = 'Please enter a valid email address.',
  EMAIL_REQUIRED = 'Please enter your email address',
  EMAIL_WHITESPACE = 'Email address must not contain leading or trailing whitespace.',
  EMAIL_NO_DOMAIN = 'Email address must contain a domain name (e.g., example.com).',
  EMAIL_NO_AT_SYMBOL = 'Email address must contain an "@" symbol',
  PASSWORD_REQUIRED = 'Please enter your password',
  PASSWORD_TOO_SHORT = 'Password must be at least 8 characters long.',
  PASSWORD_MISSING_DIGIT = 'Password must contain at least one digit.',
  PASSWORD_MISSING_UPPERCASE = 'Password must contain at least one uppercase letter.',
  PASSWORD_MISSING_LOWERCASE = 'Password must contain at least one lowercase letter.',
  PASSWORD_WHITESPACE = 'Password must not contain leading or trailing whitespace.',
  REQUIRED = 'Field is required',
  WHITESPACE = 'Email address must not contain spaces.',
  SPECIAL_CHAR = 'First name must contain only letters (no special characters or numbers)',
  ZIP_INVALID = 'Invalid postal code',
  DATE_FUTURE = 'Date cannot be in the future',
  DATE_AGE = 'You must be at least 18 years old',
}
